import { writeFileSync } from 'node:fs';

const C = {
  bg: '#f0ede8',
  water: '#a3d1f2',
  waterLine: '#87bdd4',
  park: '#c2e6b9',
  wood: '#b6d7a8',
  residential: '#edebe5',
  motorwayCasing: '#c49a3c',
  motorwayFill: '#f0c644',
  primaryCasing: '#d6cfca',
  primaryFill: '#ffffff',
  minorFill: '#ffffff',
  pathFill: '#d9d4cc',
  railway: '#d0cbc4',
  railwayDash: '#ffffff',
  aerowayFill: '#ffffff',
  aerowayCasing: '#e0dbd5',
  pier: '#edebe5',
  building: '#d9d4ca',
  buildingOutline: '#c5c0b6',
  boundaryCountry: '#777',
  boundaryState: '#999',
  labelWater: '#4a90b5',
  labelRoad: '#777',
  labelRoadHalo: '#ffffff',
  labelPlace: '#333',
  labelPlaceHalo: '#ffffff',
  ice: '#f5f5f5',
};

function z(...stops) {
  return ['interpolate', ['linear'], ['zoom'], ...stops.flat()];
}

const layers = [
  { id: 'background', type: 'background', paint: { 'background-color': C.bg } },
  {
    id: 'water', type: 'fill', source: 'openmaptiles', 'source-layer': 'water',
    filter: ['all', ['match', ['geometry-type'], ['MultiPolygon','Polygon'], true, false], ['!=', ['get','brunnel'], 'tunnel']],
    paint: { 'fill-antialias': true, 'fill-color': C.water },
  },
  {
    id: 'waterway', type: 'line', source: 'openmaptiles', 'source-layer': 'waterway',
    filter: ['match', ['geometry-type'], ['LineString','MultiLineString'], true, false],
    paint: { 'line-color': C.waterLine, 'line-width': 1.2 },
  },
  {
    id: 'landcover_ice_shelf', type: 'fill', source: 'openmaptiles', 'source-layer': 'landcover', maxzoom: 8,
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['==',['get','subclass'],'ice_shelf']],
    paint: { 'fill-color': C.ice, 'fill-opacity': 0.7 },
  },
  {
    id: 'landcover_glacier', type: 'fill', source: 'openmaptiles', 'source-layer': 'landcover', maxzoom: 8,
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['==',['get','subclass'],'glacier']],
    paint: { 'fill-color': C.ice, 'fill-opacity': z([0,1],[8,0.5]) },
  },
  {
    id: 'landcover_wood', type: 'fill', source: 'openmaptiles', 'source-layer': 'landcover', minzoom: 10,
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['==',['get','class'],'wood']],
    paint: { 'fill-color': C.wood, 'fill-opacity': z([8,0],[12,1]) },
  },
  {
    id: 'landuse_residential', type: 'fill', source: 'openmaptiles', 'source-layer': 'landuse', maxzoom: 16,
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['==',['get','class'],'residential']],
    paint: { 'fill-color': C.residential, 'fill-opacity': z([8,0.7],[10,0.5]) },
  },
  {
    id: 'park', type: 'fill', source: 'openmaptiles', 'source-layer': 'park',
    filter: ['match', ['geometry-type'], ['MultiPolygon','Polygon'], true, false],
    paint: { 'fill-color': C.park, 'fill-opacity': 0.65 },
  },
  {
    id: 'road_area_pier', type: 'fill', source: 'openmaptiles', 'source-layer': 'transportation',
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['==',['get','class'],'pier']],
    paint: { 'fill-antialias': true, 'fill-color': C.pier },
  },
  {
    id: 'tunnel_motorway_casing', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'tunnel'], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'butt', 'line-join': 'miter' },
    paint: { 'line-color': C.motorwayCasing, 'line-opacity': 1, 'line-width': z([5.8,0],[6,3],[20,40]) },
  },
  {
    id: 'tunnel_motorway_inner', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'tunnel'], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.motorwayFill, 'line-width': z([4,2],[6,1.3],[20,30]) },
  },
  {
    id: 'tunnel_major_casing', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 11,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'tunnel'], ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false]]],
    layout: { 'line-cap': 'butt', 'line-join': 'miter' },
    paint: { 'line-color': C.primaryCasing, 'line-width': z([10,3],[20,23]) },
  },
  {
    id: 'tunnel_major_inner', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 11,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'tunnel'], ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false]]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.primaryFill, 'line-width': z([10,2],[20,20]) },
  },
  {
    id: 'highway_motorway_casing', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['match',['get','brunnel'],['bridge','tunnel'],false,true], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'butt', 'line-join': 'miter' },
    paint: { 'line-color': C.motorwayCasing, 'line-opacity': 1, 'line-width': z([5.8,0],[6,3],[20,40]) },
  },
  {
    id: 'highway_motorway_inner', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['match',['get','brunnel'],['bridge','tunnel'],false,true], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': z([5.8,'#d4c4a8'],[6,C.motorwayFill]), 'line-width': z([4,2],[6,1.3],[20,30]) },
  },
  {
    id: 'highway_motorway_subtle', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', maxzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false], ['==',['get','class'],'motorway']],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': '#d4c4a8', 'line-width': z([4,2],[6,1.3]) },
  },
  {
    id: 'highway_major_casing', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 11,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false]],
    layout: { 'line-cap': 'butt', 'line-join': 'miter' },
    paint: { 'line-color': C.primaryCasing, 'line-width': z([10,3],[20,23]) },
  },
  {
    id: 'highway_major_inner', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 11,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.primaryFill, 'line-width': z([10,2],[20,20]) },
  },
  {
    id: 'highway_major_subtle', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', maxzoom: 11,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': '#ddd8d2', 'line-width': 2 },
  },
  {
    id: 'highway_minor', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 8,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['match',['get','class'],['minor','service','track'],true,false]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.minorFill, 'line-opacity': 0.95, 'line-width': z([13,1.5],[20,18]) },
  },
  {
    id: 'highway_path', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation',
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false], ['==',['get','class'],'path']],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.pathFill, 'line-opacity': 0.85, 'line-width': z([13,0.8],[20,8]) },
  },
  {
    id: 'highway_motorway_bridge_casing', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'bridge'], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'butt', 'line-join': 'miter' },
    paint: { 'line-color': C.motorwayCasing, 'line-opacity': 1, 'line-width': z([5.8,0],[6,5],[20,45]) },
  },
  {
    id: 'highway_motorway_bridge_inner', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 6,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','brunnel'],'bridge'], ['==',['get','class'],'motorway']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': z([5.8,'#d4c4a8'],[6,C.motorwayFill]), 'line-width': z([4,2],[6,1.3],[20,30]) },
  },
  {
    id: 'railway', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 13,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['!',['has','service']], ['==',['get','class'],'rail']]],
    layout: { 'line-join': 'round' },
    paint: { 'line-color': C.railway, 'line-width': z([16,3],[20,7]) },
  },
  {
    id: 'railway_dashline', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 13,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['!',['has','service']], ['==',['get','class'],'rail']]],
    layout: { 'line-join': 'round' },
    paint: { 'line-color': C.railwayDash, 'line-dasharray': [3,3], 'line-width': z([16,2],[20,6]) },
  },
  {
    id: 'railway_transit', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 16,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','class'],'transit'], ['!=',['get','brunnel'],'tunnel']]],
    layout: { 'line-join': 'round' },
    paint: { 'line-color': C.railway, 'line-width': 3 },
  },
  {
    id: 'railway_transit_dashline', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation', minzoom: 16,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['all', ['==',['get','class'],'transit'], ['!=',['get','brunnel'],'tunnel']]],
    layout: { 'line-join': 'round' },
    paint: { 'line-color': C.railwayDash, 'line-dasharray': [3,3], 'line-width': 2 },
  },
  {
    id: 'aeroway-runway-casing', type: 'line', source: 'openmaptiles', 'source-layer': 'aeroway', minzoom: 11,
    filter: ['match',['get','class'],['runway'],true,false],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.aerowayCasing, 'line-width': z([11,4],[17,50]) },
  },
  {
    id: 'aeroway-runway', type: 'line', source: 'openmaptiles', 'source-layer': 'aeroway', minzoom: 11,
    filter: ['all', ['match',['get','class'],['runway'],true,false], ['match',['geometry-type'],['LineString','MultiLineString'],true,false]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.aerowayFill, 'line-width': z([11,3],[17,44]) },
  },
  {
    id: 'aeroway-taxiway', type: 'line', source: 'openmaptiles', 'source-layer': 'aeroway', minzoom: 12,
    filter: ['match',['get','class'],['taxiway'],true,false],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.aerowayFill, 'line-width': z([12,1.5],[20,18]) },
  },
  {
    id: 'aeroway-area', type: 'fill', source: 'openmaptiles', 'source-layer': 'aeroway', minzoom: 4,
    filter: ['all', ['match',['geometry-type'],['MultiPolygon','Polygon'],true,false], ['match',['get','class'],['runway','taxiway'],true,false]],
    paint: { 'fill-color': C.aerowayFill, 'fill-opacity': z([13,0],[14,1]) },
  },
  {
    id: 'building', type: 'fill', source: 'openmaptiles', 'source-layer': 'building', minzoom: 15,
    paint: {
      'fill-antialias': true,
      'fill-color': C.building,
      'fill-opacity': z([15,0],[16,0.35],[18,0.75],[20,1]),
      'fill-outline-color': C.buildingOutline,
    },
  },
  {
    id: 'road_pier', type: 'line', source: 'openmaptiles', 'source-layer': 'transportation',
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false], ['==',['get','class'],'pier']],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: { 'line-color': C.pier, 'line-width': z([15,1],[17,4]) },
  },
  {
    id: 'boundary_2', type: 'line', source: 'openmaptiles', 'source-layer': 'boundary',
    filter: ['all', ['==',['get','admin_level'],2], ['!=',['get','maritime'],1], ['!=',['get','disputed'],1], ['!',['has','claimed_by']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': C.boundaryCountry,
      'line-opacity': z([0,0.4],[4,1]),
      'line-width': z([3,1],[5,1.2],[12,3]),
    },
  },
  {
    id: 'boundary_3', type: 'line', source: 'openmaptiles', 'source-layer': 'boundary', minzoom: 8,
    filter: ['all', ['>=',['get','admin_level'],3], ['<=',['get','admin_level'],6], ['!=',['get','maritime'],1], ['!=',['get','disputed'],1], ['!',['has','claimed_by']]],
    paint: {
      'line-color': C.boundaryState,
      'line-dasharray': [1,1],
      'line-width': z([7,1],[11,2]),
    },
  },
  {
    id: 'boundary_disputed', type: 'line', source: 'openmaptiles', 'source-layer': 'boundary',
    filter: ['all', ['!=',['get','maritime'],1], ['==',['get','disputed'],1]],
    paint: { 'line-color': C.boundaryState, 'line-dasharray': [1,2], 'line-width': z([3,1],[5,1.2],[12,3]) },
  },
  {
    id: 'water_name_point_label', type: 'symbol', source: 'openmaptiles', 'source-layer': 'water_name',
    filter: ['match', ['geometry-type'], ['MultiPoint','Point'], true, false],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Italic'],
      'text-letter-spacing': 0.15,
      'text-max-width': 5,
      'text-size': z([0,10],[8,14]),
    },
    paint: { 'text-color': C.labelWater, 'text-halo-color': 'rgba(255,255,255,0.7)', 'text-halo-width': 1.5 },
  },
  {
    id: 'water_name_line_label', type: 'symbol', source: 'openmaptiles', 'source-layer': 'water_name',
    filter: ['match', ['geometry-type'], ['LineString','MultiLineString'], true, false],
    layout: {
      'symbol-placement': 'line', 'symbol-spacing': 350,
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], ' ', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Italic'],
      'text-letter-spacing': 0.15, 'text-max-width': 5, 'text-size': 14,
    },
    paint: { 'text-color': C.labelWater, 'text-halo-color': 'rgba(255,255,255,0.7)', 'text-halo-width': 1.5 },
  },
  {
    id: 'waterway_line_label', type: 'symbol', source: 'openmaptiles', 'source-layer': 'waterway', minzoom: 10,
    filter: ['match', ['geometry-type'], ['LineString','MultiLineString'], true, false],
    layout: {
      'symbol-placement': 'line', 'symbol-spacing': 350,
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], ' ', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Italic'],
      'text-letter-spacing': 0.15, 'text-max-width': 5, 'text-size': 14,
    },
    paint: { 'text-color': C.labelWater, 'text-halo-color': 'rgba(255,255,255,0.7)', 'text-halo-width': 1.5 },
  },
  {
    id: 'highway-name-path', type: 'symbol', source: 'openmaptiles', 'source-layer': 'transportation_name', minzoom: 15.5,
    filter: ['==',['get','class'],'path'],
    layout: {
      'symbol-placement': 'line', 'text-field': ['coalesce',['get','name_en'],['get','name']],
      'text-font': ['Noto Sans Regular'], 'text-rotation-alignment': 'map',
      'text-size': z([13,11],[17,14]),
    },
    paint: { 'text-color': '#999', 'text-halo-color': C.labelRoadHalo, 'text-halo-width': 0.5 },
  },
  {
    id: 'highway-name-minor', type: 'symbol', source: 'openmaptiles', 'source-layer': 'transportation_name', minzoom: 15,
    filter: ['all', ['match',['geometry-type'],['LineString','MultiLineString'],true,false],
      ['match',['get','class'],['minor','service','track'],true,false]],
    layout: {
      'symbol-placement': 'line', 'text-field': ['coalesce',['get','name_en'],['get','name']],
      'text-font': ['Noto Sans Regular'], 'text-rotation-alignment': 'map',
      'text-size': z([14,11],[17,13]),
    },
    paint: { 'text-color': C.labelRoad, 'text-halo-blur': 0.5, 'text-halo-width': 1 },
  },
  {
    id: 'highway-name-major', type: 'symbol', source: 'openmaptiles', 'source-layer': 'transportation_name', minzoom: 12.2,
    filter: ['match',['get','class'],['primary','secondary','tertiary','trunk'],true,false],
    layout: {
      'symbol-placement': 'line', 'text-field': ['coalesce',['get','name_en'],['get','name']],
      'text-font': ['Noto Sans Regular'], 'text-rotation-alignment': 'map',
      'text-size': z([13,11],[17,14]),
    },
    paint: { 'text-color': '#555', 'text-halo-blur': 0.5, 'text-halo-width': 1 },
  },
  {
    id: 'label_poi', type: 'symbol', source: 'openmaptiles', 'source-layer': 'poi', minzoom: 12,
    filter: ['all', ['!=',['get','name'],'']],
    layout: {
      'text-field': ['coalesce',['get','name_en'],['get','name']],
      'text-font': ['Noto Sans Regular'],
      'text-size': z([12,10],[16,12]),
      'text-anchor': 'center', 'text-optional': true, 'text-max-width': 8,
    },
    paint: { 'text-color': '#555', 'text-halo-color': '#ffffff', 'text-halo-width': 1 },
  },
  {
    id: 'label_country_1', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', maxzoom: 9,
    filter: ['all', ['==',['get','class'],'country'], ['==',['get','rank'],1]],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Bold'], 'text-max-width': 6.25,
      'text-size': z([1,9],[4,17]),
    },
    paint: { 'text-color': C.labelPlace, 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_country_2', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', maxzoom: 9,
    filter: ['all', ['==',['get','class'],'country'], ['==',['get','rank'],2]],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Bold'], 'text-max-width': 6.25,
      'text-size': z([2,9],[5,17]),
    },
    paint: { 'text-color': C.labelPlace, 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_country_3', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 2, maxzoom: 9,
    filter: ['all', ['==',['get','class'],'country'], ['>=',['get','rank'],3]],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Bold'], 'text-max-width': 6.25,
      'text-size': z([3,9],[7,17]),
    },
    paint: { 'text-color': C.labelPlace, 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_state', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 5, maxzoom: 8,
    filter: ['==',['get','class'],'state'],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Italic'],
      'text-letter-spacing': 0.15, 'text-max-width': 9,
      'text-size': z([5,10],[8,14]),
      'text-transform': 'uppercase',
    },
    paint: { 'text-color': '#666', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_city_capital', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 3,
    filter: ['all', ['==',['get','class'],'city'], ['==',['get','capital'],2]],
    layout: {
      'icon-allow-overlap': true,
      'icon-image': ['step',['zoom'], 'circle_11_black', 9, ''],
      'icon-optional': false, 'icon-size': 0.45,
      'text-anchor': 'bottom',
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Bold'], 'text-max-width': 8,
      'text-offset': [0, -0.15],
      'text-size': z([4,12],[7,14],[11,20]),
    },
    paint: { 'text-color': '#222', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1.2 },
  },
  {
    id: 'label_city', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 3,
    filter: ['all', ['==',['get','class'],'city'], ['!=',['get','capital'],2]],
    layout: {
      'icon-allow-overlap': true,
      'icon-image': ['step',['zoom'], 'circle_11_black', 9, ''],
      'icon-optional': false, 'icon-size': 0.35,
      'text-anchor': 'bottom',
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Regular'], 'text-max-width': 8,
      'text-offset': [0, -0.1],
      'text-size': z([4,11],[7,13],[11,18]),
    },
    paint: { 'text-color': '#333', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_town', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 6,
    filter: ['==',['get','class'],'town'],
    layout: {
      'icon-allow-overlap': true,
      'icon-image': ['step',['zoom'], 'circle_11_black', 10, ''],
      'icon-optional': false, 'icon-size': 0.2,
      'text-anchor': 'bottom',
      'text-field': ['coalesce', ['get','name_en'], ['get','name']],
      'text-font': ['Noto Sans Regular'], 'text-max-width': 8,
      'text-size': z([7,11],[11,14]),
    },
    paint: { 'text-color': '#444', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 1 },
  },
  {
    id: 'label_village', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 9,
    filter: ['==',['get','class'],'village'],
    layout: {
      'icon-allow-overlap': true,
      'icon-image': ['step',['zoom'], 'circle_11_black', 10, ''],
      'icon-optional': false, 'icon-size': 0.18,
      'text-anchor': 'bottom',
      'text-field': ['coalesce', ['get','name_en'], ['get','name']],
      'text-font': ['Noto Sans Regular'], 'text-max-width': 8,
      'text-size': z([7,10],[11,12]),
    },
    paint: { 'text-color': '#666', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 0.8 },
  },
  {
    id: 'label_other', type: 'symbol', source: 'openmaptiles', 'source-layer': 'place', minzoom: 8,
    filter: ['match',['get','class'],['city','continent','country','state','town','village'],false,true],
    layout: {
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Italic'],
      'text-letter-spacing': 0.1, 'text-max-width': 9,
      'text-size': z([8,9],[12,10]),
      'text-transform': 'uppercase',
    },
    paint: { 'text-color': '#888', 'text-halo-blur': 1, 'text-halo-color': C.labelPlaceHalo, 'text-halo-width': 0.8 },
  },
  {
    id: 'airport', type: 'symbol', source: 'openmaptiles', 'source-layer': 'aerodrome_label', minzoom: 11,
    filter: ['all', ['has','iata']],
    layout: {
      'icon-image': 'airport_11', 'icon-size': 1,
      'text-anchor': 'top',
      'text-field': ['case', ['has','name:nonlatin'],
        ['concat', ['get','name:latin'], '\n', ['get','name:nonlatin']],
        ['coalesce', ['get','name_en'], ['get','name']]],
      'text-font': ['Noto Sans Regular'],
      'text-max-width': 9, 'text-offset': [0,0.6],
      'text-optional': true, 'text-padding': 2, 'text-size': 12,
    },
    paint: { 'text-color': '#555', 'text-halo-blur': 0.5, 'text-halo-color': '#ffffff', 'text-halo-width': 1 },
  },
];

const style = {
  version: 8,
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'pmtiles://__PMTILES_URL__',
      attribution: '© OpenStreetMap contributors · TransferCuba',
    },
  },
  sprite: 'https://tiles.openfreemap.org/sprites/ofm_f384/ofm',
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  layers,
};

writeFileSync(
  '/media/Akdulay/27B09181315B1AF22/TransferCuba/public/map/transfercuba-style.json',
  JSON.stringify(style, null, 2),
);
console.log('Written', layers.length, 'layers to transfercuba-style.json');
